/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Register;

import java.awt.Color;
import GestionUsuarios.GestionUsuarios;

/**
 *
 * @author Emiliano Castro
 */
public class PaginaRegistro extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public PaginaRegistro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new javax.swing.JPanel();
        ImagenLogoGrande = new javax.swing.JLabel();
        NombreEmpresa = new javax.swing.JLabel();
        FondoLogo = new javax.swing.JLabel();
        LogoPequeño = new javax.swing.JLabel();
        NombreEmpresaPequeño = new javax.swing.JLabel();
        IniciarSesion = new javax.swing.JLabel();
        Usuario = new javax.swing.JLabel();
        SeparadorContraseña = new javax.swing.JSeparator();
        SeparadorNombreDeUsuario = new javax.swing.JSeparator();
        NombreUsuario = new javax.swing.JTextField();
        TextoContraseña = new javax.swing.JLabel();
        SeparadorRepetirContraseña = new javax.swing.JSeparator();
        RepetirPass = new javax.swing.JPasswordField();
        BotonRegistrarse = new javax.swing.JButton();
        TextoContraseña1 = new javax.swing.JLabel();
        Pass1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Fondo.setBackground(new java.awt.Color(255, 255, 255));
        Fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ImagenLogoGrande.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ImagenLogoGrande.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imagen empresa en circulo.png"))); // NOI18N
        Fondo.add(ImagenLogoGrande, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, 380, -1));

        NombreEmpresa.setFont(new java.awt.Font("Caveat", 1, 48)); // NOI18N
        NombreEmpresa.setForeground(new java.awt.Color(255, 102, 0));
        NombreEmpresa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NombreEmpresa.setText("\"Mis Sabores\"");
        Fondo.add(NombreEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 480, 380, 90));

        FondoLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo.jpg"))); // NOI18N
        FondoLogo.setText("jLabel2");
        Fondo.add(FondoLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 380, 750));

        LogoPequeño.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo minimalista con.png"))); // NOI18N
        Fondo.add(LogoPequeño, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 50, -1));

        NombreEmpresaPequeño.setFont(new java.awt.Font("Caveat", 1, 18)); // NOI18N
        NombreEmpresaPequeño.setForeground(new java.awt.Color(255, 102, 0));
        NombreEmpresaPequeño.setText("Mis Sabores");
        Fondo.add(NombreEmpresaPequeño, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 80, 50));

        IniciarSesion.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        IniciarSesion.setText("Registrarse");
        Fondo.add(IniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 280, 130));

        Usuario.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        Usuario.setText("Nombre de usuario");
        Fondo.add(Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 170, 50));

        SeparadorContraseña.setBackground(new java.awt.Color(0, 0, 0));
        SeparadorContraseña.setForeground(new java.awt.Color(0, 0, 0));
        Fondo.add(SeparadorContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, 390, 30));

        SeparadorNombreDeUsuario.setBackground(new java.awt.Color(0, 0, 0));
        SeparadorNombreDeUsuario.setForeground(new java.awt.Color(0, 0, 0));
        Fondo.add(SeparadorNombreDeUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 390, 30));

        NombreUsuario.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        NombreUsuario.setForeground(new java.awt.Color(153, 153, 153));
        NombreUsuario.setBorder(null);
        NombreUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                NombreUsuarioMousePressed(evt);
            }
        });
        NombreUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreUsuarioActionPerformed(evt);
            }
        });
        Fondo.add(NombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 390, 50));

        TextoContraseña.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        TextoContraseña.setText("Repita su contraseña");
        TextoContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TextoContraseñaMousePressed(evt);
            }
        });
        Fondo.add(TextoContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 450, 190, 40));

        SeparadorRepetirContraseña.setBackground(new java.awt.Color(0, 0, 0));
        SeparadorRepetirContraseña.setForeground(new java.awt.Color(0, 0, 0));
        Fondo.add(SeparadorRepetirContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 520, 390, 30));

        RepetirPass.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        RepetirPass.setForeground(new java.awt.Color(153, 153, 153));
        RepetirPass.setBorder(null);
        RepetirPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                RepetirPassMousePressed(evt);
            }
        });
        RepetirPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RepetirPassActionPerformed(evt);
            }
        });
        Fondo.add(RepetirPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, 390, 50));

        BotonRegistrarse.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        BotonRegistrarse.setText("REGISTRARSE");
        BotonRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegistrarseActionPerformed(evt);
            }
        });
        Fondo.add(BotonRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 590, 170, 60));

        TextoContraseña1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        TextoContraseña1.setText("Contraseña");
        TextoContraseña1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TextoContraseña1MousePressed(evt);
            }
        });
        Fondo.add(TextoContraseña1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 190, 40));

        Pass1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        Pass1.setForeground(new java.awt.Color(153, 153, 153));
        Pass1.setBorder(null);
        Pass1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Pass1MousePressed(evt);
            }
        });
        Pass1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pass1ActionPerformed(evt);
            }
        });
        Fondo.add(Pass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 390, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NombreUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreUsuarioActionPerformed

    private void NombreUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NombreUsuarioMousePressed
        NombreUsuario.setText("");
        NombreUsuario.setForeground(Color.BLACK);
       
        
    }//GEN-LAST:event_NombreUsuarioMousePressed

    private void RepetirPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RepetirPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RepetirPassActionPerformed

    private void RepetirPassMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RepetirPassMousePressed
        RepetirPass.setText("");
        RepetirPass.setForeground(Color.black);
    }//GEN-LAST:event_RepetirPassMousePressed

    private void TextoContraseñaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextoContraseñaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoContraseñaMousePressed

    private void BotonRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegistrarseActionPerformed
        GestionUsuarios gestion = new GestionUsuarios();
        String appNombre = NombreUsuario.getText();
        char[] pass1 = Pass1.getPassword();
        char[] pass2 = RepetirPass.getPassword();
        String appPassword = new String(pass1);
        String appPassword2 = new String(pass2);
        gestion.registroUsuario(appNombre, appPassword, appPassword2);
    }//GEN-LAST:event_BotonRegistrarseActionPerformed

    private void TextoContraseña1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextoContraseña1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoContraseña1MousePressed

    private void Pass1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pass1MousePressed
        Pass1.setText("");
        Pass1.setForeground(Color.black);
    }//GEN-LAST:event_Pass1MousePressed

    private void Pass1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pass1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pass1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaginaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaginaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaginaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaginaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaginaRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonRegistrarse;
    private javax.swing.JPanel Fondo;
    private javax.swing.JLabel FondoLogo;
    private javax.swing.JLabel ImagenLogoGrande;
    private javax.swing.JLabel IniciarSesion;
    private javax.swing.JLabel LogoPequeño;
    private javax.swing.JLabel NombreEmpresa;
    private javax.swing.JLabel NombreEmpresaPequeño;
    private javax.swing.JTextField NombreUsuario;
    private javax.swing.JPasswordField Pass1;
    private javax.swing.JPasswordField RepetirPass;
    private javax.swing.JSeparator SeparadorContraseña;
    private javax.swing.JSeparator SeparadorNombreDeUsuario;
    private javax.swing.JSeparator SeparadorRepetirContraseña;
    private javax.swing.JLabel TextoContraseña;
    private javax.swing.JLabel TextoContraseña1;
    private javax.swing.JLabel Usuario;
    // End of variables declaration//GEN-END:variables
}
