/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ProgramaVentas;

import Gestion.GestionProductos;
import java.awt.Color;
/**
 *
 * @author Emiliano Castro
 */
public class PagAñadirStock extends javax.swing.JPanel {

    /**
     * Creates new form PagInicio
     */
    public PagAñadirStock() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        Fondo = new javax.swing.JPanel();
        AgregarStock = new javax.swing.JButton();
        PanelAñadirStock = new javax.swing.JPanel();
        PalabraAñadirStock = new javax.swing.JLabel();
        PrecioVenta = new javax.swing.JTextField();
        NombreProducto = new javax.swing.JTextField();
        CodigoProducto = new javax.swing.JTextField();
        StockProducto = new javax.swing.JTextField();
        PrecioCompra = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        FeedBack = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("jLabel1");

        Fondo.setBackground(new java.awt.Color(255, 255, 255));
        Fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AgregarStock.setBackground(new java.awt.Color(255, 107, 107));
        AgregarStock.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        AgregarStock.setForeground(new java.awt.Color(51, 51, 51));
        AgregarStock.setText("GUARDAR");
        AgregarStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarStockActionPerformed(evt);
            }
        });
        Fondo.add(AgregarStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 710, 70));

        PanelAñadirStock.setBackground(new java.awt.Color(239, 253, 255));

        PalabraAñadirStock.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        PalabraAñadirStock.setForeground(new java.awt.Color(0, 119, 182));
        PalabraAñadirStock.setText("Añadir Stock");

        javax.swing.GroupLayout PanelAñadirStockLayout = new javax.swing.GroupLayout(PanelAñadirStock);
        PanelAñadirStock.setLayout(PanelAñadirStockLayout);
        PanelAñadirStockLayout.setHorizontalGroup(
            PanelAñadirStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAñadirStockLayout.createSequentialGroup()
                .addGap(0, 20, Short.MAX_VALUE)
                .addComponent(PalabraAñadirStock, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PanelAñadirStockLayout.setVerticalGroup(
            PanelAñadirStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAñadirStockLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PalabraAñadirStock, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Fondo.add(PanelAñadirStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 80));

        PrecioVenta.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        PrecioVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PrecioVentaMousePressed(evt);
            }
        });
        Fondo.add(PrecioVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 700, 40));

        NombreProducto.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        NombreProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                NombreProductoMousePressed(evt);
            }
        });
        Fondo.add(NombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 700, 40));

        CodigoProducto.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        CodigoProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CodigoProductoMousePressed(evt);
            }
        });
        Fondo.add(CodigoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 700, 40));

        StockProducto.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        StockProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        StockProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                StockProductoMousePressed(evt);
            }
        });
        Fondo.add(StockProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 700, 40));

        PrecioCompra.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        PrecioCompra.setToolTipText("");
        PrecioCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PrecioCompraMousePressed(evt);
            }
        });
        Fondo.add(PrecioCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 700, 40));

        jLabel2.setFont(new java.awt.Font("Caveat", 1, 12)); // NOI18N
        jLabel2.setText("PRECIO DE VENTA");
        Fondo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 180, 30));

        jLabel3.setFont(new java.awt.Font("Caveat", 1, 12)); // NOI18N
        jLabel3.setText("NOMBRE DEL PRODUCTO");
        Fondo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 180, 30));

        jLabel4.setFont(new java.awt.Font("Caveat", 1, 12)); // NOI18N
        jLabel4.setText("CODIGO DEL PRODUCTO");
        Fondo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 180, 30));

        jLabel5.setFont(new java.awt.Font("Caveat", 1, 12)); // NOI18N
        jLabel5.setText("STOCK DEL PRODUCTO");
        Fondo.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 180, 30));

        jLabel6.setFont(new java.awt.Font("Caveat", 1, 12)); // NOI18N
        jLabel6.setText("PRECIO DE COMPRA");
        Fondo.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 180, 30));

        FeedBack.setFont(new java.awt.Font("Caveat", 1, 18)); // NOI18N
        Fondo.add(FeedBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 570, 430, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarStockActionPerformed
        String Nombre = NombreProducto.getText().trim();
        String Codigo = CodigoProducto.getText().trim();
        String stockT = StockProducto.getText().trim();
        String precioCompraT = PrecioCompra.getText().trim();
        String precioVentaT = PrecioVenta.getText().trim();
        int precioCompra =  Integer.parseInt(precioCompraT);
        int stock = Integer.parseInt(stockT);
        int precioVenta = Integer.parseInt(precioVentaT);
        
        GestionProductos g = new GestionProductos();
        g.itemExiste(Codigo);
        
        if (Nombre.isBlank()){
            FeedBack.setText("El nombre no puede estar vacio");
        }
        if (Codigo.isBlank()){
            FeedBack.setText("El codigo no puede estar vacio");
        }
         if (stock < 1){
            FeedBack.setText("El Stock no puede ser menor a 1");
        }
        if (precioCompra < 1){
            FeedBack.setText("El Precio de compra no puede ser menor a 1");
        }
        if (precioVenta < 1){
            FeedBack.setText("El precio de venta no puede ser menor a 1");
        }
        if (g.itemExiste(Codigo) == null && !Codigo.isBlank()){
            g.crearItem(Nombre, Codigo, stock, precioCompra, precioVenta);
            FeedBack.setText("Item creado correctamente");
        }
        
        
    }//GEN-LAST:event_AgregarStockActionPerformed

    private void NombreProductoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NombreProductoMousePressed
        NombreProducto.setText("");
        NombreProducto.setForeground(Color.black);
    }//GEN-LAST:event_NombreProductoMousePressed

    private void PrecioVentaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PrecioVentaMousePressed
        PrecioVenta.setText("");
        PrecioVenta.setForeground(Color.black);
    }//GEN-LAST:event_PrecioVentaMousePressed

    private void PrecioCompraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PrecioCompraMousePressed
        PrecioCompra.setText("");
        PrecioCompra.setForeground(Color.black);
    }//GEN-LAST:event_PrecioCompraMousePressed

    private void CodigoProductoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CodigoProductoMousePressed
        CodigoProducto.setText("");
        CodigoProducto.setForeground(Color.black);
    }//GEN-LAST:event_CodigoProductoMousePressed

    private void StockProductoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StockProductoMousePressed
        StockProducto.setText("");
        StockProducto.setForeground(Color.black);
    }//GEN-LAST:event_StockProductoMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarStock;
    private javax.swing.JTextField CodigoProducto;
    private javax.swing.JLabel FeedBack;
    private javax.swing.JPanel Fondo;
    private javax.swing.JTextField NombreProducto;
    private javax.swing.JLabel PalabraAñadirStock;
    private javax.swing.JPanel PanelAñadirStock;
    private javax.swing.JTextField PrecioCompra;
    private javax.swing.JTextField PrecioVenta;
    private javax.swing.JTextField StockProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
