/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ProgramaVentas;

/**
 *
 * @author Emiliano Castro
 */
public class PagInicio extends javax.swing.JPanel {

    /**
     * Creates new form PagInicio
     */
    public PagInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Fondo = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        PalabraInicio = new javax.swing.JLabel();
        PanelInicio = new javax.swing.JPanel();
        NombreDelProducto = new javax.swing.JLabel();
        CodigoDelProducto = new javax.swing.JLabel();
        Stock = new javax.swing.JLabel();
        PrecioDeCompra = new javax.swing.JLabel();
        PrecioDeVenta = new javax.swing.JLabel();
        BotonCobrar = new javax.swing.JButton();
        Total = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        Fondo.setBackground(new java.awt.Color(255, 255, 255));
        Fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(210, 249, 245));
        jButton1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setText("AGREGAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Fondo.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, 90, 40));

        jTextField1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(153, 153, 153));
        jTextField1.setText("Ingrese el codigo del producto");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        Fondo.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 270, 40));

        PalabraInicio.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        PalabraInicio.setForeground(new java.awt.Color(0, 119, 182));
        PalabraInicio.setText("Inicio");
        Fondo.add(PalabraInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 730, 80));

        PanelInicio.setBackground(new java.awt.Color(239, 253, 255));

        javax.swing.GroupLayout PanelInicioLayout = new javax.swing.GroupLayout(PanelInicio);
        PanelInicio.setLayout(PanelInicioLayout);
        PanelInicioLayout.setHorizontalGroup(
            PanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PanelInicioLayout.setVerticalGroup(
            PanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        Fondo.add(PanelInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 80));

        NombreDelProducto.setText("Nombre Del Producto");
        Fondo.add(NombreDelProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 120, -1));

        CodigoDelProducto.setText("Codigo Del Producto");
        Fondo.add(CodigoDelProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 120, -1));

        Stock.setText("Stock");
        Fondo.add(Stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, -1, -1));

        PrecioDeCompra.setText("Precio De Compra");
        Fondo.add(PrecioDeCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, -1, -1));

        PrecioDeVenta.setText("Precio De Venta");
        Fondo.add(PrecioDeVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 80, -1, -1));

        BotonCobrar.setBackground(new java.awt.Color(255, 107, 107));
        BotonCobrar.setFont(new java.awt.Font("Roboto", 0, 48)); // NOI18N
        BotonCobrar.setForeground(new java.awt.Color(51, 51, 51));
        BotonCobrar.setText("Cobrar");
        BotonCobrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCobrarActionPerformed(evt);
            }
        });
        Fondo.add(BotonCobrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 720, 70));

        Total.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        Total.setForeground(new java.awt.Color(0, 119, 182));
        Total.setText("Total:");
        Fondo.add(Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 720, 40));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        Fondo.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 750, 10));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        Fondo.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 750, 10));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        Fondo.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 20, 360));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        Fondo.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 80, 20, 360));

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        Fondo.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 20, 360));

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);
        Fondo.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 20, 360));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BotonCobrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCobrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonCobrarActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonCobrar;
    private javax.swing.JLabel CodigoDelProducto;
    private javax.swing.JPanel Fondo;
    private javax.swing.JLabel NombreDelProducto;
    private javax.swing.JLabel PalabraInicio;
    private javax.swing.JPanel PanelInicio;
    private javax.swing.JLabel PrecioDeCompra;
    private javax.swing.JLabel PrecioDeVenta;
    private javax.swing.JLabel Stock;
    private javax.swing.JLabel Total;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
