/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ProgramaVentas;

import javax.swing.table.DefaultTableModel;
import Gestion.GestionProductos;
import Gestion.Item;
import java.util.List;
import Gestion.Fecha;
import Gestion.GestionVentas;
/**
 *
 * @author Emiliano Castro
 */
public class PagInicio extends javax.swing.JPanel {
        
   DefaultTableModel dtm = new DefaultTableModel();
    /**
     * Creates new form PagInicio
     */
    public PagInicio() {
        initComponents();
        Venta.setModel(dtm);
        String titulos[] = {"Nombre del Producto", "Codigo del Producto", "Cantidad", "Precio"};
        dtm.setColumnIdentifiers(titulos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Fondo = new javax.swing.JPanel();
        Agregar = new javax.swing.JButton();
        CANTIDAD = new javax.swing.JTextField();
        CODPRODUCTO = new javax.swing.JTextField();
        TotalCantidad = new javax.swing.JLabel();
        Limpiar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PalabraInicio = new javax.swing.JLabel();
        PanelInicio = new javax.swing.JPanel();
        BotonCobrar = new javax.swing.JButton();
        Total = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Venta = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        Fondo.setBackground(new java.awt.Color(255, 255, 255));
        Fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Agregar.setBackground(new java.awt.Color(210, 249, 245));
        Agregar.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        Agregar.setForeground(new java.awt.Color(51, 51, 51));
        Agregar.setText("AGREGAR");
        Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarActionPerformed(evt);
            }
        });
        Fondo.add(Agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 30, 90, 40));

        CANTIDAD.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        CANTIDAD.setForeground(new java.awt.Color(153, 153, 153));
        CANTIDAD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CANTIDADMousePressed(evt);
            }
        });
        Fondo.add(CANTIDAD, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, 90, 40));

        CODPRODUCTO.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        CODPRODUCTO.setForeground(new java.awt.Color(153, 153, 153));
        CODPRODUCTO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CODPRODUCTOMousePressed(evt);
            }
        });
        Fondo.add(CODPRODUCTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 90, 40));

        TotalCantidad.setFont(new java.awt.Font("Caveat", 1, 36)); // NOI18N
        Fondo.add(TotalCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, 520, 50));

        Limpiar.setBackground(new java.awt.Color(255, 107, 107));
        Limpiar.setFont(new java.awt.Font("Roboto", 0, 48)); // NOI18N
        Limpiar.setText("Limpiar");
        Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarActionPerformed(evt);
            }
        });
        Fondo.add(Limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 510, 220, 70));

        jLabel1.setFont(new java.awt.Font("Caveat", 1, 14)); // NOI18N
        jLabel1.setText("COD PRODUCTO");
        Fondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 90, -1));

        jLabel2.setFont(new java.awt.Font("Caveat", 1, 14)); // NOI18N
        jLabel2.setText("CANTIDAD");
        Fondo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 70, -1));

        PalabraInicio.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        PalabraInicio.setForeground(new java.awt.Color(0, 119, 182));
        PalabraInicio.setText("Inicio");
        Fondo.add(PalabraInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 730, 80));

        PanelInicio.setBackground(new java.awt.Color(239, 253, 255));

        javax.swing.GroupLayout PanelInicioLayout = new javax.swing.GroupLayout(PanelInicio);
        PanelInicio.setLayout(PanelInicioLayout);
        PanelInicioLayout.setHorizontalGroup(
            PanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PanelInicioLayout.setVerticalGroup(
            PanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        Fondo.add(PanelInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 80));

        BotonCobrar.setBackground(new java.awt.Color(102, 204, 0));
        BotonCobrar.setFont(new java.awt.Font("Roboto", 0, 48)); // NOI18N
        BotonCobrar.setForeground(new java.awt.Color(51, 51, 51));
        BotonCobrar.setText("Cobrar");
        BotonCobrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCobrarActionPerformed(evt);
            }
        });
        Fondo.add(BotonCobrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 510, 230, 70));

        Total.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        Total.setForeground(new java.awt.Color(0, 119, 182));
        Total.setText("Total:");
        Fondo.add(Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 110, 40));

        Venta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(Venta);

        Fondo.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 80, 750, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BotonCobrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCobrarActionPerformed
        GestionVentas v = new GestionVentas();
        Fecha f = new Fecha();
        int contador = dtm.getRowCount();
        double totalVenta = 0.0;
        for (int i = 0; i < contador; i++){
        
            Object cantidadObj = dtm.getValueAt(i, 2);
            Object precioObj = dtm.getValueAt(i, 3);
            
            if (cantidadObj != null && precioObj != null) {
                
               int cantidadFila = Integer.parseInt(cantidadObj.toString());
               double precioVenta = Double.parseDouble(precioObj.toString());
                
                double totalVentaMulti = cantidadFila * precioVenta;
                totalVenta += totalVentaMulti;
            }
        }
        
        v.insertarVenta(v.getLargoLista(), totalVenta, f.getFechaActual());
        
       
        
    }//GEN-LAST:event_BotonCobrarActionPerformed

    private void AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarActionPerformed
        GestionProductos g = new GestionProductos();
        String producto = CODPRODUCTO.getText().trim();
        String cantidadT = CANTIDAD.getText().trim();
        int cantidad = Integer.parseInt(cantidadT);
        
        if (g.itemExiste(producto)!= null){
         dtm.addRow(new Object[] {
         g.itemExiste(producto).getNombre(),
         g.itemExiste(producto).getCodigo(),
         cantidad,
         g.itemExiste(producto).getPrecioVenta()});
        }
        else {
            System.out.println("El item no existe");
        }
        
        int contador = dtm.getRowCount();
        double totalVenta = 0.0;
        for (int i = 0; i < contador; i++){
        
            Object cantidadObj = dtm.getValueAt(i, 2);
            Object precioObj = dtm.getValueAt(i, 3);
            
            if (cantidadObj != null && precioObj != null) {
                
               int cantidadFila = Integer.parseInt(cantidadObj.toString());
               double precioVenta = Double.parseDouble(precioObj.toString());
                
                double totalVentaMulti = cantidadFila * precioVenta;
                totalVenta += totalVentaMulti;
                
                
            }
          TotalCantidad.setText(String.valueOf(totalVenta));  
          CANTIDAD.setText("");
          CODPRODUCTO.setText("");
        }
    }//GEN-LAST:event_AgregarActionPerformed

    private void CODPRODUCTOMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CODPRODUCTOMousePressed
        CODPRODUCTO.setText("");   
    }//GEN-LAST:event_CODPRODUCTOMousePressed

    private void CANTIDADMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CANTIDADMousePressed
       CANTIDAD.setText("");
    }//GEN-LAST:event_CANTIDADMousePressed

    private void LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarActionPerformed
        dtm.setRowCount(0);
        CANTIDAD.setText("");
        CODPRODUCTO.setText("");
        TotalCantidad.setText("");
    }//GEN-LAST:event_LimpiarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar;
    private javax.swing.JButton BotonCobrar;
    private javax.swing.JTextField CANTIDAD;
    private javax.swing.JTextField CODPRODUCTO;
    private javax.swing.JPanel Fondo;
    private javax.swing.JButton Limpiar;
    private javax.swing.JLabel PalabraInicio;
    private javax.swing.JPanel PanelInicio;
    private javax.swing.JLabel Total;
    private javax.swing.JLabel TotalCantidad;
    private javax.swing.JTable Venta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
