/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ProgramaVentas;

import java.util.HashSet;
import java.util.Set;
import javax.swing.table.DefaultTableModel;
import Gestion.GestionProductos;
import Gestion.Item;
import java.util.List;

/**
 *
 * @author Emiliano Castro
 */
public class PagStock extends javax.swing.JPanel {
    
    DefaultTableModel dtm = new DefaultTableModel();
    /**
     * Creates new form PagInicio
     */
    public PagStock() {
        initComponents();
        TablaStock.setModel(dtm);
        String titulos[] = {"Nombre del Producto","Codigo del Producto","Stock","Precio de Compra", "Precio de Venta"};
        dtm.setColumnIdentifiers(titulos);
        GestionProductos g = new GestionProductos();
    List<Item> todosLosItems = g.muestraCompleta();
    
    // Agregar CADA item a la tabla
    for (Item item : todosLosItems) {
        String nombre = item.getNombre();
        String codigo = item.getCodigo();
        int stock = item.getStock();
        double precioCompra = item.getPrecioCompra();
        double precioVenta = item.getPrecioVenta();
        
        dtm.addRow(new Object[] {nombre, codigo, stock, precioCompra, precioVenta});
    }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Fondo = new javax.swing.JPanel();
        PalabraStock = new javax.swing.JLabel();
        PanelStock = new javax.swing.JPanel();
        IngreseNombreDelProducto = new javax.swing.JTextField();
        BOTONLISTACOMP = new javax.swing.JButton();
        BOTONBUSQ = new javax.swing.JButton();
        PalabraBusqueda = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaStock = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        Fondo.setBackground(new java.awt.Color(255, 255, 255));
        Fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PalabraStock.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        PalabraStock.setForeground(new java.awt.Color(0, 119, 182));
        PalabraStock.setText("Stock");
        Fondo.add(PalabraStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 730, 80));

        PanelStock.setBackground(new java.awt.Color(239, 253, 255));

        javax.swing.GroupLayout PanelStockLayout = new javax.swing.GroupLayout(PanelStock);
        PanelStock.setLayout(PanelStockLayout);
        PanelStockLayout.setHorizontalGroup(
            PanelStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        PanelStockLayout.setVerticalGroup(
            PanelStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        Fondo.add(PanelStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 80));

        IngreseNombreDelProducto.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        IngreseNombreDelProducto.setForeground(new java.awt.Color(153, 153, 153));
        IngreseNombreDelProducto.setText("Ingrese nombre del producto");
        IngreseNombreDelProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IngreseNombreDelProductoMouseClicked(evt);
            }
        });
        Fondo.add(IngreseNombreDelProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 500, 220, 50));

        BOTONLISTACOMP.setText("LISTA COMPLETA");
        BOTONLISTACOMP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTONLISTACOMPActionPerformed(evt);
            }
        });
        Fondo.add(BOTONLISTACOMP, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 500, 180, 50));

        BOTONBUSQ.setText("BUSCAR");
        BOTONBUSQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTONBUSQActionPerformed(evt);
            }
        });
        Fondo.add(BOTONBUSQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 500, 130, 50));

        PalabraBusqueda.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        PalabraBusqueda.setForeground(new java.awt.Color(0, 119, 182));
        PalabraBusqueda.setText("Busqueda:");
        Fondo.add(PalabraBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 740, 70));

        TablaStock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre del Producto", "Codigo del Producto", "Stock", "Precio de Compra", "Precio de Venta"
            }
        ));
        jScrollPane2.setViewportView(TablaStock);

        Fondo.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 77, 750, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BOTONBUSQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTONBUSQActionPerformed
        GestionProductos g = new GestionProductos();
        dtm.setRowCount(0);
        String itemBuscado = IngreseNombreDelProducto.getText();
        
        dtm.addRow(new Object[] {
         g.itemExiste(itemBuscado).getNombre(),
         g.itemExiste(itemBuscado).getCodigo(),
         g.itemExiste(itemBuscado).getStock(),
         g.itemExiste(itemBuscado).getPrecioCompra(),
         g.itemExiste(itemBuscado).getPrecioVenta()});
        
        IngreseNombreDelProducto.setText("");
    }//GEN-LAST:event_BOTONBUSQActionPerformed

    private void IngreseNombreDelProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IngreseNombreDelProductoMouseClicked
        IngreseNombreDelProducto.setText("");
        
    }//GEN-LAST:event_IngreseNombreDelProductoMouseClicked

    private void BOTONLISTACOMPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTONLISTACOMPActionPerformed
    GestionProductos g = new GestionProductos();
    List<Item> todosLosItems = g.muestraCompleta();
    
    // Agregar CADA item a la tabla
    for (Item item : todosLosItems) {
        String nombre = item.getNombre();
        String codigo = item.getCodigo();
        int stock = item.getStock();
        double precioCompra = item.getPrecioCompra();
        double precioVenta = item.getPrecioVenta();
        
        dtm.addRow(new Object[] {nombre, codigo, stock, precioCompra, precioVenta});
    }
    }//GEN-LAST:event_BOTONLISTACOMPActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BOTONBUSQ;
    private javax.swing.JButton BOTONLISTACOMP;
    private javax.swing.JPanel Fondo;
    private javax.swing.JTextField IngreseNombreDelProducto;
    private javax.swing.JLabel PalabraBusqueda;
    private javax.swing.JLabel PalabraStock;
    private javax.swing.JPanel PanelStock;
    private javax.swing.JTable TablaStock;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
