/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ProgramaVentas;

/**
 *
 * @author Emiliano Castro
 */
public class PagStock extends javax.swing.JPanel {

    /**
     * Creates new form PagInicio
     */
    public PagStock() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Fondo = new javax.swing.JPanel();
        PalabraStock = new javax.swing.JLabel();
        PanelStock = new javax.swing.JPanel();
        NombreDelProducto = new javax.swing.JLabel();
        CodigoDelProducto = new javax.swing.JLabel();
        Stock = new javax.swing.JLabel();
        PrecioDeCompra = new javax.swing.JLabel();
        PrecioDeVenta = new javax.swing.JLabel();
        IngreseNombreDelProducto = new javax.swing.JTextField();
        PalabraBusqueda = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        Fondo.setBackground(new java.awt.Color(255, 255, 255));
        Fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PalabraStock.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        PalabraStock.setForeground(new java.awt.Color(0, 119, 182));
        PalabraStock.setText("Stock");
        Fondo.add(PalabraStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 730, 80));

        PanelStock.setBackground(new java.awt.Color(239, 253, 255));

        javax.swing.GroupLayout PanelStockLayout = new javax.swing.GroupLayout(PanelStock);
        PanelStock.setLayout(PanelStockLayout);
        PanelStockLayout.setHorizontalGroup(
            PanelStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        PanelStockLayout.setVerticalGroup(
            PanelStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        Fondo.add(PanelStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 80));

        NombreDelProducto.setText("Nombre Del Producto");
        Fondo.add(NombreDelProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 120, -1));

        CodigoDelProducto.setText("Codigo Del Producto");
        Fondo.add(CodigoDelProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 120, -1));

        Stock.setText("Stock");
        Fondo.add(Stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, -1, -1));

        PrecioDeCompra.setText("Precio De Compra");
        Fondo.add(PrecioDeCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, -1, -1));

        PrecioDeVenta.setText("Precio De Venta");
        Fondo.add(PrecioDeVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 80, -1, -1));

        IngreseNombreDelProducto.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        IngreseNombreDelProducto.setForeground(new java.awt.Color(153, 153, 153));
        IngreseNombreDelProducto.setText("Ingrese nombre del producto");
        Fondo.add(IngreseNombreDelProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 510, 520, 40));

        PalabraBusqueda.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        PalabraBusqueda.setForeground(new java.awt.Color(0, 119, 182));
        PalabraBusqueda.setText("Busqueda:");
        Fondo.add(PalabraBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 740, 70));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        Fondo.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 750, 10));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        Fondo.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 750, 10));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        Fondo.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 20, 360));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        Fondo.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 80, 20, 360));

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        Fondo.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 20, 360));

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);
        Fondo.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 20, 360));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CodigoDelProducto;
    private javax.swing.JPanel Fondo;
    private javax.swing.JTextField IngreseNombreDelProducto;
    private javax.swing.JLabel NombreDelProducto;
    private javax.swing.JLabel PalabraBusqueda;
    private javax.swing.JLabel PalabraStock;
    private javax.swing.JPanel PanelStock;
    private javax.swing.JLabel PrecioDeCompra;
    private javax.swing.JLabel PrecioDeVenta;
    private javax.swing.JLabel Stock;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
