/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ProgramaVentas;
import javax.swing.table.DefaultTableModel;
import Gestion.GestionVentas;
import Gestion.Venta;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;

/**
 *
 * @author Emiliano Castro
 */
public class PagVentas extends javax.swing.JPanel {
    DefaultTableModel dtm = new DefaultTableModel();
    /**
     * Creates new form PagInicio
     */
    public PagVentas() {
        initComponents();
        
        tablaVentas.setModel(dtm);
        String titulos[] = {"Venta","Total","Fecha"};
        dtm.setColumnIdentifiers(titulos);
        GestionVentas v = new GestionVentas();
        List<Venta> todasLasVentas = v.muestraCompletaVentas();
        
        for (Venta venta : todasLasVentas) {
        int idVenta = venta.getIdVenta();
        double totalVenta = venta.gettotalVenta();
        String fecha = venta.fechaActual();
        dtm.addRow(new Object[] {idVenta, totalVenta, fecha});
        }
        
        
        
        int contador = dtm.getRowCount();
        double totalVenta = 0.0;
        for (int i = 0; i < contador; i++){
        
            Object totalVentaObj = dtm.getValueAt(i, 1);
            Object fechaVentaObj = dtm.getValueAt(i, 2);
            
            if (totalVentaObj!= null && fechaVentaObj != null) {
                
               // Convertir el total
        double totalVentaDia = Double.parseDouble(totalVentaObj.toString());
        
        // Convertir y comparar la fecha
        String fechaVentaStr = fechaVentaObj.toString();
        DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        LocalDate fechaVenta = LocalDate.parse(fechaVentaStr, formato);
        
        // Solo sumar si la venta es de hoy
        if (fechaVenta.equals(LocalDate.now())) {
            totalVenta += totalVentaDia;
        }
            }
       TotalVentas.setText(String.valueOf(totalVenta));
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Fondo = new javax.swing.JPanel();
        PalabraInicio = new javax.swing.JLabel();
        PanelInicio = new javax.swing.JPanel();
        TotalVentas = new javax.swing.JLabel();
        Total = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaVentas = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        Fondo.setBackground(new java.awt.Color(255, 255, 255));
        Fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PalabraInicio.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        PalabraInicio.setForeground(new java.awt.Color(0, 119, 182));
        PalabraInicio.setText("Ventas");
        Fondo.add(PalabraInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 730, 80));

        PanelInicio.setBackground(new java.awt.Color(239, 253, 255));

        javax.swing.GroupLayout PanelInicioLayout = new javax.swing.GroupLayout(PanelInicio);
        PanelInicio.setLayout(PanelInicioLayout);
        PanelInicioLayout.setHorizontalGroup(
            PanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        PanelInicioLayout.setVerticalGroup(
            PanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        Fondo.add(PanelInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 80));

        TotalVentas.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        Fondo.add(TotalVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 510, 210, 40));

        Total.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        Total.setForeground(new java.awt.Color(0, 119, 182));
        Total.setText("Recaudación de hoy:");
        Fondo.add(Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 740, 70));

        tablaVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tablaVentas);

        Fondo.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 750, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Fondo;
    private javax.swing.JLabel PalabraInicio;
    private javax.swing.JPanel PanelInicio;
    private javax.swing.JLabel Total;
    private javax.swing.JLabel TotalVentas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tablaVentas;
    // End of variables declaration//GEN-END:variables
}
