/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package LoginDeUsuario;

import java.awt.Color;
import GestionUsuarios.GestionUsuarios;
import GestionUsuarios.Usuario;

/**
 *
 * @author Emiliano Castro
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new javax.swing.JPanel();
        ImagenLogoGrande = new javax.swing.JLabel();
        NombreEmpresa = new javax.swing.JLabel();
        FondoLogo = new javax.swing.JLabel();
        LogoPequeño = new javax.swing.JLabel();
        NombreEmpresaPequeño = new javax.swing.JLabel();
        IniciarSesion = new javax.swing.JLabel();
        Usuario = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        NombreUsuario = new javax.swing.JTextField();
        TextoContraseña = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        Pass = new javax.swing.JPasswordField();
        BotonIniciar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Fondo.setBackground(new java.awt.Color(255, 255, 255));
        Fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ImagenLogoGrande.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ImagenLogoGrande.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imagen empresa en circulo.png"))); // NOI18N
        Fondo.add(ImagenLogoGrande, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, 380, -1));

        NombreEmpresa.setFont(new java.awt.Font("Caveat", 1, 48)); // NOI18N
        NombreEmpresa.setForeground(new java.awt.Color(255, 102, 0));
        NombreEmpresa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NombreEmpresa.setText("\"Mis Sabores\"");
        Fondo.add(NombreEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 480, 380, 90));

        FondoLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo.jpg"))); // NOI18N
        FondoLogo.setText("jLabel2");
        Fondo.add(FondoLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 380, 750));

        LogoPequeño.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo minimalista con.png"))); // NOI18N
        Fondo.add(LogoPequeño, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 50, -1));

        NombreEmpresaPequeño.setFont(new java.awt.Font("Caveat", 1, 18)); // NOI18N
        NombreEmpresaPequeño.setForeground(new java.awt.Color(255, 102, 0));
        NombreEmpresaPequeño.setText("Mis Sabores");
        Fondo.add(NombreEmpresaPequeño, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 80, 50));

        IniciarSesion.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        IniciarSesion.setText("INICIAR SESIÓN");
        Fondo.add(IniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 280, 130));

        Usuario.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        Usuario.setText("USUARIO");
        Fondo.add(Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 150, 50));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        Fondo.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 390, -1));

        NombreUsuario.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        NombreUsuario.setForeground(new java.awt.Color(153, 153, 153));
        NombreUsuario.setText("Ingrese su nombre de usuario");
        NombreUsuario.setBorder(null);
        NombreUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                NombreUsuarioMousePressed(evt);
            }
        });
        NombreUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreUsuarioActionPerformed(evt);
            }
        });
        Fondo.add(NombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 390, 50));

        TextoContraseña.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        TextoContraseña.setText("CONTRASEÑA");
        TextoContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TextoContraseñaMousePressed(evt);
            }
        });
        Fondo.add(TextoContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, 120, 40));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        Fondo.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 510, 390, 30));

        Pass.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        Pass.setForeground(new java.awt.Color(153, 153, 153));
        Pass.setText("********");
        Pass.setBorder(null);
        Pass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PassMousePressed(evt);
            }
        });
        Pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PassActionPerformed(evt);
            }
        });
        Fondo.add(Pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, 390, 50));

        BotonIniciar.setBackground(new java.awt.Color(249, 117, 15));
        BotonIniciar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        BotonIniciar.setForeground(new java.awt.Color(255, 255, 255));
        BotonIniciar.setText("INICIAR");
        BotonIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonIniciarActionPerformed(evt);
            }
        });
        Fondo.add(BotonIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 580, 200, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NombreUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreUsuarioActionPerformed

    private void BotonIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonIniciarActionPerformed
        GestionUsuarios gestion = new GestionUsuarios();
        String appEmail = NombreUsuario.getText();
        char[] Password = Pass.getPassword();
        String appPassword = new String(Password);
        gestion.inicioSesion(appEmail, appPassword);
    }//GEN-LAST:event_BotonIniciarActionPerformed

    private void NombreUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NombreUsuarioMousePressed
        NombreUsuario.setText("");
        NombreUsuario.setForeground(Color.BLACK);
        
        
    }//GEN-LAST:event_NombreUsuarioMousePressed

    private void PassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PassActionPerformed

    private void PassMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PassMousePressed
        Pass.setText("");
        Pass.setForeground(Color.black);
    }//GEN-LAST:event_PassMousePressed

    private void TextoContraseñaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextoContraseñaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoContraseñaMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonIniciar;
    private javax.swing.JPanel Fondo;
    private javax.swing.JLabel FondoLogo;
    private javax.swing.JLabel ImagenLogoGrande;
    private javax.swing.JLabel IniciarSesion;
    private javax.swing.JLabel LogoPequeño;
    private javax.swing.JLabel NombreEmpresa;
    private javax.swing.JLabel NombreEmpresaPequeño;
    private javax.swing.JTextField NombreUsuario;
    private javax.swing.JPasswordField Pass;
    private javax.swing.JLabel TextoContraseña;
    private javax.swing.JLabel Usuario;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
